/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "STM32F103C6.h"
#include "GPIO.h"
#include "keypad.h"
#include "lcd.h"
#include "USART.h"
#include "SPI.h"
#include "I2C.h"
#include "TIMER.h"
#include "app.h"

void UART_CALLBACK ();

uint8 x= 'a';
uint8 uart1_Data;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

SPI_Config_t spi_master= {
		.BaudRate_Prescaler=BAUDERATE_PRESCALER_2,
		.CLK_Phase=CLK_PHASE_FIRST,
		.CLK_Polarity=CLK_POLARITY_IDLE_LOW,
		.Communication_Mode=COMMUNICATION_MODE_2LINE_FULL_DUPLEX,
		.Frame_Format=FRAME_FORMAT_MSB_FIRST,
		.Frame_Size=FRAME_SIZE_8BIT,
		.NSS=NSS_SW_SSI_RESET,
		.SPI_Mode=SPI_MODE_MASTER,
		.SPIx=SPI1,
		.TXE_INT_EN=0,
		.RXNE_INT_EN=0,
		.ERRI_INT_EN=0,
		.SPI1_IRQ_CallBack=NULL,
		.SPI2_IRQ_CallBack=NULL
};

UART_Config uart1={
		.BaudRate =9600,
		.HwFlowCtl=UART_HwFlowCtl_NONE,
		.PEIE_IRQ_Enable=0,
		.P_IRQ_CallBack= UART_CALLBACK,
		.Parity=UART_Parity__NONE,
		.Payload_Length= UART_Payload_Length_8B,
		.RXNEIE_IRQ_Enable=1,
		.StopBits=UART_StopBits__1,
		.TCIE_IRQ_Enable=0,
		.TXEIE_IRQ_Enable=0,
		.USART_Mode =UART_MODE_TX_RX,
		.USARTx= USART1
};
void UART_CALLBACK (){
	uart1_Data=USART1->DR;
	MCAL_UART_SendData(&uart1, &uart1_Data, 1);
	MCAL_SPI_Send_Data(&spi_master, &uart1_Data, 1);

}

int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	MCAL_SPI_Init(&spi_master);
	MCAL_SPI_GPIO_Set_Pins(&spi_master);
	MCAL_UART_Init(&uart1);
	MCAL_UART_GPIO_Set_Pins(&uart1);


	while (1){

//		MCAL_SPI_Send_Data(&spi_master, &x, 1);
		delay_ms(10);


	}
}


